class Student:
    def __init__(self, name, house):
        self.name = name
        self.house = house

    def __str__(self):
        return f"{self.name} from {self.house}"

    @property
    def name(self):
        return self._name

    @name.setter
    def name(self, name):
        if not name:
            raise ValueError("Missing name")
        self._name = name

    @property
    def house(self):
        return self._house

    @house.setter
    def house(self, house):
        if house not in ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"]:
            raise ValueError("Invalid house")
        self._house = house


def main():
    student = get_student()
    student._house = "Number Four, Privet Drive"  # Voltou a explorar o erro de substituição de valores, agora com
    # Setter e Getter implementados. student.house resulta em "ValueError: Invalid house" e student._house resulta em
    # "Harry from Number Four, Privet Drive". Isso significa que o "_" impediu a checagem do erro previamente setado.
    print(student)


def get_student():
    name = input("Name: ")
    house = input("House: ")
    return Student(name, house)


if __name__ == "__main__":
    main()
